version: '3'

services:
  etoolservice-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - etoolservicenet

    
  etoolservice-api:
    restart: unless-stopped
    build: .
    volumes:
      - './Data/Images/Products:/app/Data/Images/Products'
    environment:
      - ConnectionStrings:EToolServiceDB=Server=etoolservice-sql,1433;Database=EToolServiceDocker;User=sa;Password=QWElkj132!;ConnectRetryCount=0;MultipleActiveResultSets=true
    ports:
      - 5000:80
    networks:
      - etoolservicenet
    links:
      - etoolservice-sql
    depends_on:
      - etoolservice-sql
      
networks:
  etoolservicenet:
    driver: bridge
